import { formatTime } from '../src/lib/race.js';

const escape = text => String(text).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);

export function reviewHTML(proposal, rider, course) {
  const all = [...course.points, ...proposal.trace];
  const minLat = Math.min(...all.map(p => p.lat)), maxLat = Math.max(...all.map(p => p.lat));
  const minLon = Math.min(...all.map(p => p.lon)), maxLon = Math.max(...all.map(p => p.lon));
  const cos = Math.cos((minLat + maxLat) / 2 * Math.PI / 180);
  const scale = Math.min(640 / ((maxLon - minLon) * cos || 1), 440 / (maxLat - minLat || 1));
  const draw = points => points.map((p, i) => `${i ? 'L' : 'M'}${(30 + (p.lon - minLon) * cos * scale).toFixed(1)},${(470 - (p.lat - minLat) * scale).toFixed(1)}`).join(' ');
  return `<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Проверка FIT · ${escape(rider.name)}</title><style>body{font:16px/1.6 system-ui;max-width:850px;padding:25px;margin:auto;color:#263120;background:#f7f8f4}h1{font-size:30px}strong{font-size:22px}svg{width:100%;max-height:500px;background:white;border:1px solid #ddd;border-radius:8px}dt{font-weight:bold}dd{margin:0 0 10px}code{overflow-wrap:anywhere}li{margin-bottom:12px}.warning{background:#fff2ce;padding:15px;border-radius:6px}.legend{display:flex;gap:25px}</style><h1>${escape(rider.name)} · проверка FIT</h1><p>Локальный черновик. В зачёт ещё не включён.</p><strong>${formatTime(proposal.elapsedSeconds)}</strong><dl><dt>Старт (UTC)</dt><dd>${escape(proposal.startedAt)}</dd><dt>Финиш (UTC)</dt><dd>${escape(proposal.finishedAt || 'не найден')}</dd><dt>GPS-дистанция</dt><dd>${(proposal.distanceM / 1000).toFixed(2)} км</dd><dt>Контрольные точки</dt><dd>${proposal.checkpointsMatched} / ${proposal.checkpointsTotal}</dd></dl>${proposal.warnings.length ? `<div class="warning"><b>Требует проверки</b><ul>${proposal.warnings.map(w => `<li>${escape(w)}</li>`).join('')}</ul></div>` : '<p>Последовательность контрольных точек совпала. Сверьте отметки старта и финиша: ожидание у старта и неточный GPS могут влиять на время.</p>'}<p class="legend"><span style="color:#79952e">Зелёный — GPX</span><span style="color:#2e77b0">Синий — FIT</span></p><svg viewBox="0 0 700 500" role="img" aria-label="Сравнение маршрута и записи"><path d="${draw(course.points)}" fill="none" stroke="#9eb945" stroke-width="5"/><path d="${draw(proposal.trace)}" fill="none" stroke="#2e77b0" stroke-width="2"/></svg><p>Для исправления времени повторите импорт с <code>--start ISO --finish ISO --replace</code>. Всегда указывайте часовой пояс.</p><p>После проверки: <code>npm run approve -- --rider ${escape(rider.id)}</code>. При предупреждениях добавьте <code>--note "Что проверено и почему результат принимается"</code>.</p></html>`;
}
